### ISSUE TITLE
Error on git dir

### ISSUE THREAD

**Issue by woutercleymans** [phpro/grumphp#1]
Grumphp expects that the git root is in the same folder as the vendor folder.

Directory structure:
–– app
–––– .git
–––– .gitignore
–––– src
–––––– grumphp.yml
–––––– vendor
–––––––– phpro
–––––––––– grumphp

**Comment by aderuwe** [comment]
`echo $(git rev-parse --show-toplevel)` prints the path to the folder containing .git from anywhere within the repository.
Probably should use something like that.

**Comment by veewee** [comment]
The git commands are only available in GitElephant when the repository is already created.
That is why we need to know to location of the root folder before running the CLI.
Anyway, it might be a good idea to implement the rev-parse in a future version!

I guess this issue is due to a bad config path in the git hook with the folder structure mentioned above.
This might be solved by adding a post-install script that will ask the installer about the project structure if no grumphp.yml file could be found at the same location as the composer.json file.

@woutercleymans Can you try to set the correct config path?

**Comment by woutercleymans** [comment]
It works when I change the value of git_dir in the grumphp.yml file.
before: ```git_dir: "./.."```
after: ```git_dir: "./"```

@aderuwe good solution, but what if you're using submodules like vagrant?

**Comment by veewee** [comment]
The correct configuration for the git_dir is '..' in your context.
Please check v0.1.3, this issue should be fixed!
