### ISSUE TITLE
Feature Request: generate a nice report for CI

### ISSUE THREAD

**Issue by obriat** [phpro/grumphp#1006]
Hi,

It would be great to generate a nice formatted report when using grumphp on a CI. 

Phpunit and  code climate formats seems the most commons one ?

**Comment by veewee** [comment]
Hello, thanks for reporting.
The format as it is right now is quite ok to me.
Since we run a lot of tasks, there is no ready way to report it all 
We rely on the tools underneath to do so.

You could for example use any formatter of phpunit to generate a report specific for your tests. Any tool can be formatted independently.


If you do have a concrete solution in mind, feel free to share it.
If it's better - it's better right 🙂
