### ISSUE TITLE
Support for AMPHP v3

### ISSUE THREAD

**Issue by stof** [phpro/grumphp#1064]
Currently, grumphp requires AMPHP v2. It would be great if it could support both v2 and v3 to avoid blocking upgrades in projects using grumphp.

**Comment by veewee** [comment]
Idd surely accept a PR for that.
Last time I checked, amphp/parallel didn't have a stable release yet?

**Comment by veewee** [comment]
Good news, a amp 3 compatible version of parallel got released today
https://github.com/amphp/parallel/releases/tag/v2.0.0

**Comment by stof** [comment]
but parallel-functions does not have a compatible version yet

**Comment by trowski** [comment]
So I've had this page open on my laptop for about 2 months now, meaning to say I'd be happy to help transition this package to use `amphp/parallel` instead of `amphp/parallel-functions` as no further versions of that package is planned.

@stof You opening an issue kicked me to actually make a post. I'm not sure when I could promise any time, but I'd be happy to answer questions if someone more familiar with the library wants to tackle it first.

**Comment by veewee** [comment]
Thanks for jumping on on the discussion @trowski.
Really love the work you did on amp!

I'm planning to play around with amp v3 and GrumPHP for the rest of the day.
This will probably result in a draft PR on which we can discuss how to do specific things.

**Comment by veewee** [comment]
A small update: I think I covered all existing grumphp cases with amp v3 in the PR #1084.

I was able to throw away a lot of strange quirks I needed to add to get things like stop-on-failure and parallel-functions to work in v2 of amp. It's nice to see how much the project has improved! Great stuff!

Feel free to go through the PR and suggest improvements if I missed or misused anything :)

**Comment by veewee** [comment]
Feel free to play around with the v2.x branch;
I'm planning to add some other breaking changes before releasing it. In the meantime : all feedback is welcome.
