### ISSUE TITLE
Symfony 2.6 dependencies

### ISSUE THREAD

**Issue by klipach** [phpro/grumphp#13]
In `composer.json` all Symfony components require version 2.6 or above, but a lot of projects use Symfony 2.3 (like mine) because it is an LTS release. Is it possible to downgrade component versions to 2.3?

**Comment by veewee** [comment]
Hello @klipach,
I agree we should use the LTS version as the minimum version for Symfony.
Symfony ^2.3 seems the way to go for GrumPHP.
The solution requires some extra testing on all platforms to make sure everything is still working!

**Comment by veewee** [comment]
The composer.json is changed on the master branch so that you can use Symfony 2.3.
Commit: https://github.com/phpro/grumphp/commit/d12b1d6c5f0d5a80a0b71a1e1c4ad7f2dd8c607f

The package we use for git actions, requires symfony process 2.4. 
This results in an unresolvable error: 
`Your requirements could not be resolved to an installable set of packages.`

I created a ticket on the official repository:
https://github.com/gitonomy/gitlib/issues/85

When this ticket is resolved, I will be testing with Symfony 2.3 on Linux and Windows.

**Comment by klipach** [comment]
Yesterday i checked the same solution locally, i had a problem with dependency injection https://github.com/phpro/grumphp/blob/master/resources/config/services.yml#L42 there is no support for expression engine for DI 2.3 https://github.com/symfony/DependencyInjection/blob/2.3/composer.json

**Comment by veewee** [comment]
This means that the lowest we can currently go without modifying the code is Symfony 2.4.
I will still need to test with version 2.4 to make sure all features will work.

**Comment by klipach** [comment]
it is no so easy to downgrade to fit Symfony LTS version. I think you can close this ticket.

**Comment by veewee** [comment]
LTS is probably not possible. But we will aim to make the Symfony version as low as possible.
V2.4 might work. I will keep this ticket open until we tested with some projects.

**Comment by veewee** [comment]
It seems to work with Symfony 2.4. So that will be our minimum dependency.
