### ISSUE TITLE
Autoload issue

### ISSUE THREAD

**Issue by cdekok** [phpro/grumphp#170]
I had some problems with the wrong symfony/console library being used the problem eventually came down to the vendor dir from my parent project was being used while i was working on a lib from inside the vendor dir.

This project changes the current working dir as is common on ZF2 projects, that is why it loaded.

projects/vendor
instead of
projects/vendor/library/vendor

Can we change the order of the autoload path so that the parent directory comes above the one with the getcwd.

https://github.com/phpro/grumphp/blob/master/bin/grumphp#L7

**Comment by veewee** [comment]
No, the order is made this way because it is also possible to run GrumPHP as a global executable. 
When we place the `__DIR__` entries first, the global packages will be used instead of the local packages.

ZF2 indeed changes the current working dir in it's `public/index.php`. GrumPHP is totally unaware of this change since it does not use this `index.php` file. In your package it should also be unaware of the working directory, since it is determined in the application.

Maybe a possible solution would be to use a path repository: https://getcomposer.org/doc/05-repositories.md#path
You set the code in a separate folder and work in that folder. Your package has to work in a closed scope, independent off the application you are working on.
Next the package can be symlinked in your real application.

**Comment by cdekok** [comment]
Ah yes forgot that it can be installed globally too, will have a look at the path settings didn't know about the before.
