### ISSUE TITLE
Add support for git_pre_push

### ISSUE THREAD

**Issue by Mte90** [phpro/grumphp#252]
| Q               | A
| --------------- | ---
| Branch          | master for features and deprecations
| New feature?    | yes

As example I don't want to run codeception at every commit but only at every push but the hook `git_pre_push` is not available.

**Comment by veewee** [comment]
Great idea!

**Comment by Mte90** [comment]
I can try to work on this one, any suggestions where to start to hack?
I guess that require an installation part to inject the hooks in the git folder.

**Comment by Mte90** [comment]
started to experiment with #258

**Comment by veewee** [comment]
It looks like you are starting out well. :)

**Comment by tworzenieweb** [comment]
First of all thanks for introducing this feature. What is the current state of work?

**Comment by Mte90** [comment]
that the pr is waiting the last final approval.
As I see now the unit tests got an errore but I have no time anymore to continue to work on that so if someone can do a fix and do a pr on pr I think that everything is done.

**Comment by Mte90** [comment]
Just an updated because I was looking if someone else implemented it.
RIght now my pr was rejected for a lot of different reasons and I have no time to work on that, so if someone has time and want to implement it can move on #258.

**Comment by veewee** [comment]
Since detecting the changelog is quite hard, I think it is sufficient to just put `grumphp run` inside the `pre-push` git hook if you want to use it.
You could even specify a test suite to choose which tasks you want to run.

I don't think we should add anything in order to make it work at this moment.
Gonna close this issue for now. Feel free to add your insights to this issue or create a PR if we do need to change something.
