### ISSUE TITLE
Reduce dependencies down to absolute minimum required

### ISSUE THREAD

**Issue by Bilge** [phpro/grumphp#272]
| Q               | A
| --------------- | ---
| Branch          | what
| Bug?            | no
| New feature?    | no
| Question?       | kinda
| Documentation?  | no
| Related tickets | n/a

The list of mandatory dependencies is excessive. I'd like to think many of them could be moved to either suggested or dev dependencies either immediately or with a little work. Let's make GrumPHP lighter.

**Comment by patkar** [comment]
Especially the `composer/composer` dependency is a little bit harmful. We have `export PATH=./vendor/bin:$PATH` on our systems to ease the use of composer installed devtools like phpspec and co. The developer can simply execute `phpspec` instead of `vendor/bin/phpspec`. Now the installed composer dependency writes a `vendor/bin/composer` and this "overwrites" the usage of the global composer. So a `composer install/update` now executes your required composer package in vendor.

**Comment by stof** [comment]
Installing composer itself looks indeed quite weird. What is the reason to have it as a dependency ?

For composer plugins, the code runs inside a composer process anyway, and so already has access to the composer classes (and installing composer a second time could even do weird things). If it is only for testing the composer plugin, it should be a dev requirement.
