### ISSUE TITLE
Cannot commit because of two execs in pre-commit

### ISSUE THREAD

**Issue by hoffmannjonas** [phpro/grumphp#339]
Version: 0.11.3
Bug: yes

I cannot run a commit becasue of two execs in pre-commit hook:
```
#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

# Fetch the GIT diff and format it as command input:
DIFF=$(git diff -r -p -m -M --full-index --staged | cat)

# Run GrumPHP
(cd "${HOOK_EXEC_PATH}" && printf "%s\n" "${DIFF}" | exec exec $(HOOK_COMMAND) '--skip-success-output')
```

Can easily be fixed by removing an exec

**Comment by veewee** [comment]
Hi @hoffmannjonas,

Thanks for reporting this issue.

Can you tell me which preset you are using?
As far as I can see, there is only one exec in the template:
https://github.com/phpro/grumphp/blob/master/resources/hooks/local/pre-commit

**Comment by phux** [comment]
Please check [PR 352](https://github.com/phpro/grumphp/pull/352).

**Comment by veewee** [comment]
This is a Symfony Process related issue:

It looks like this additional exec is added by the Symfony Process component here in this PR: symfony/symfony#21474
This issue mentions the break: symfony/symfony#22476
And a PR is on it's way: symfony/symfony#22476

Since the fix is not merged yet, you can solve this issue in your own project by copying the adjusted git hook templates from #352 and use the hooks_dir parameter (https://github.com/phpro/grumphp/blob/master/doc/parameters.md) .
