### ISSUE TITLE
What's the purpose of the Windows doc page

### ISSUE THREAD

**Issue by Daniel15** [phpro/grumphp#404]
What's the purpose of this page? https://github.com/phpro/grumphp/blob/master/doc/installation/windows.md. I was confused after reading "If you are trying to install GrumPHP on Windows: please read the windows pre-install section" in the readme, but there doesn't seem to be anything different about the Windows installation? It'd be exactly the same as any other platform...?

**Comment by veewee** [comment]
Hello @Daniel15,

Thanks for reporting! The page was added because people that didn't have those tools in their path were reporting bugs. I do agree that those tools are rather standard and that it also applies to all other operating systems. But windows and CLI still isn't what it should be .... Feel free to improve the documentation.
