### ISSUE TITLE
Global grumphp or grumphp.phar (like phpunit)

### ISSUE THREAD

**Issue by TheRatG** [phpro/grumphp#42]
Hello, thanks for your library.

I suggest add new feature - run hook by grumphp.phar

Advantages:
* you don't need modify your composer
* global check your code command
* self-update packet

**Comment by TheRatG** [comment]
https://github.com/box-project/box2 - create box

**Comment by veewee** [comment]
That would indeed be a nice feature. Now it is possible to use `composer global require`, but you would have to change the path of the git hook manually.

**Comment by igormukhingmailcom** [comment]
I can help with this. Have some experience with tasks like that :)

**Comment by veewee** [comment]
Maybe it's a better idea to use composer for this?
```sh
composer global require phpro/grumphp
```

This way, GrumPHP will be installed globally in the ~/.composer/vendor/bin.
Update is as easy as=
```sh
composer global update phpro/grmphp
```

Looks easier then creating phar + self-update stuff, since everybody is using composer these days.
In the git hooks we will need to add something like:

```sh
PATH=$PATH:/full/path/to/project/vendor/bin
```
This way we can change the command to just `grumphp`. It will first search all your system include paths (in which the global composer vendor/bin directory is added). When no script is found, it will use the one from the project vendor/bin directory.

What are your thoughts on this solution? A phar looks one step too far for me, since it can easliy be done with composer.

**Comment by veewee** [comment]
This one is implemented as mentioned above.
More information:
https://github.com/phpro/grumphp#global-installation

**Comment by ihsanudin** [comment]
I think is better use phar as optional. Like others php tool (php-cs-fixer, deployer, and many more) has own phar file for simplifying the task.

I think many people more familiar with phar instead of global package in composer.

**Comment by ihsanudin** [comment]
https://github.com/vinkla/climb/pull/28

**Comment by ihsanudin** [comment]
The reason why you need phar file instead of global composer
