### ISSUE TITLE
FR: extract php_parser task

### ISSUE THREAD

**Issue by keradus** [phpro/grumphp#439]
| Q               | A
| --------------- | ---
| Version         | n/a
| Bug?            | no
| New feature?    | kind of
| Question?       | no
| Documentation?  | no
| Related tickets | n/a

Hi ;)
Most of the tasks are wrappers for well-known stand-alone tools, eg phpunit tasks is a wrapper for PHPUnit library&tool.

It is great to have grumphp as a unified runner for all of them, yet I discovered that it is not the case for task build on top of php parser. While `nikic/php-parser` library is a parser, the task adds a "linting" logic, not only run a tool and manage the outcome.
This means it is not possible to use that "linting" logic standalone, without installing whole grumphp.
Please, could you consider, for usability and single responsibility, extracting it to dedicated package and at grumphp just run it?

**Comment by veewee** [comment]
Hi @keradus,

Indeed: there are some tasks that have some internal code.
Here is a short list:

- phpparser
- xmllint
- jsonlint
- yamllint

They were all created because there weren't tools available at the time that I wrote those.
Feel free to extract the logic out of this repository inside a new tool.
I would love to get the code merged out at some point :)

**Comment by keradus** [comment]
let us catch up on private channel then ;)

**Comment by veewee** [comment]
It is probably a better idea to deprecate the php_parser and promote tools like phpstan or psalm to do these kind of tasks. 
Closing this issue for now.
