### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Kanti** [phpro/grumphp#445]
| Q               | A
| --------------- | ---
| Version         | `grumphp -V`
| Bug?            | no
| New feature?    | yes
| Question?       | yes
| Documentation?  | yes/no
| Related tickets | -

Since grumphp has different tests and some can fail. We could generate a junit.xml test result.

This could be useful. As an example in [Bitbucket Pipelines](https://confluence.atlassian.com/bitbucket/test-reporting-in-pipelines-939708543.html).

What do you think about such a feature?

**Comment by Snaver** [comment]
Hey @Kanti 

I believe this is already possible! I managed to get this up and running with bitbucket pipelines this week actually.

It's possible to setup without any direct changes to grumphp. What I did was add some additional configuration options to phpunit.xml:

```
<logging>
    <log type="junit" target="./test-reports/junit.xml" />
</logging>
```

**Comment by Kanti** [comment]
Thank you @Snaver.

This is not what I meant.
It would be nice if the results of all the tasks run by grumphp are saved into a `test-reports/grumphp-junit.xml` file.
Not the result of the unit tests.

**Comment by veewee** [comment]
Hello @Kanti,

I am not sure how you would like to structure the data in the junit file since it doesn't matches what GrumPHP does. E.g.: A failure element requires a className, but we are just running external tools so we mostly don't know that info.

You could create reports by adding event listeners to your configuration:
https://github.com/phpro/grumphp/blob/master/doc/events.md

**Comment by Kanti** [comment]
Hmm ok I will look into the event listeners. Thanks a lot!
