### ISSUE TITLE
Exotic structure with Composer and GrumPHP in subfolder compared to GIT

### ISSUE THREAD

**Issue by mattheo-geoffray** [phpro/grumphp#592]
| Q               | A
| --------------- | ---
| Version         | 0.14.3
| Bug?            | yes
| New feature?    |no
| Question?       | yes
| Documentation?  | no
| Related tickets | /

Exotic project structure is wrong for GIT diff

Here is my project structure
```
/.git
/project
    |- src
        |- Namespace
            |- Vendor
    |- composer.json
    |- composer.lock
    |- grumphp.yml
```
**My configuration**
`grumphp.yml`
```yaml
parameters:
  git_dir: ".."
  bin_dir: "./project/vendor/bin"
[...]
```
`composer.json` it is a simplified version of it. The framework behind is a Magento 2
```json
{
    "require-dev": {
        "pdepend/pdepend": "2.5.2",
        "phpmd/phpmd": "^2.6",
        "phpro/grumphp": "^0.14",
        "phpunit/phpunit": "~6.5.0",
        "sebastian/phpcpd": "^3.0",
        "sensiolabs/security-checker": "^5.0",
        "slevomat/coding-standard": "~4.0",
        "squizlabs/php_codesniffer": "^3.3"
    },
    "autoload": {
        "psr-0": {
            "": [
                "src/"
            ]
        },
    },
    "extra": {
        "grumphp": {
            "config-default-path": "grumphp.yml"
        }
    }
}
```

**Steps to reproduce:**
```sh
cd project
composer install
# modifying a file in project/src/*
git commit -m "reproducing GrumPHP issue"
```

**Result:**
GrumPHP is not sniffing the file modified by GIT.

When I check the `\GrumPHP\Console\Command\Git\PreCommitCommand::getCommittedFiles` there is no file in it.  
The `\GrumPHP\Locator\ChangedFiles::locateFromRawDiffInput`
=> I have the good GIT diff
```sh
project/src/*.php
```
The error is in `\GrumPHP\Locator\ChangedFiles::parseFilesFromDiff`
Where 
```php
if ($file->isDeletion() || !$this->filesystem->exists($fileObject->getPathname())) {
    continue;
}

!$this->filesystem->exists($fileObject->getPathname() => Return false
```
One simple test in `\GrumPHP\Locator\ChangedFiles::parseFilesFromDiff`
```php 
file_exist('project/src/*.php') => return false

file_exist('src/*.php') => return true
```

My guess is that the root for Composer is in `project` but the GIT root is above `project`, so the autoloader have the wrong path.

I don't think it is a GrumPHP bug it more probably an exotic structure maybe not supported by GrumPHP logic.   
  
Do you have a solution for that?

Thank you!

**Comment by mattheo-geoffray** [comment]
Little information we use that structure because it is a dockerized application so we can not have the Composer at the project root

**Comment by malc0mn** [comment]
I'm having the exact same issue. This project structure is not at all exotic, just a clean way to separate, for example, source from documentation and preventing your git repo to become a mess :smile: 

Whenever I make a change, it **seems** as though GrumPHP is doing it's thing, running all tasks, but you can make whatever coding error you want without any of the tasks detecting it.

I have also traced the problem and have an idea for a solution as well:

1. When we look at the git hooks being installed, the pre-commit hook looks like this:
```bash
#!/bin/sh

#
# Run the hook command.
# Note: this will be replaced by the real command during copy.
#

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)

# Run GrumPHP
(cd "${HOOK_EXEC_PATH}" && printf "%s\n" "${DIFF}" | exec $(HOOK_COMMAND) '--skip-success-output')
```
2. You see that a subfolder is handled perfectly because of the `cd "${HOOK_EXEC_PATH}"` in the very last line.
3. The problem, however, is the git diff that is being generated, which will look like this:
```diff
diff --git a/project/src/path/to/my/file.php b/project/src/path/to/my/file.php
index c9bdffd945057f1202a27c150dc8512139eab3a0..ec20fbe03e4a01d40445716892f6162562a8dd73 100644
--- a/project/src/path/to/my/BaseController.php
+++ b/project/src/path/to/my/BaseController.php
@@ -33,7 +33,7 @@ abstract class BaseController extends Controller
             if ($log) {
                 $this->log($log, 'error');
             }
-            throw $this->createAccessDeniedException($message);
+throw $this->createAccessDeniedException($message);
         }
     }
```
The problem should be obvious instantly when looking at the paths: they start from the very root of the git repository.

**Possible solutions**:
1. Given the fact that you know the `HOOK_EXEC_PATH`, you can easily strip this path from the git diff that you receive

2. I'm not at all sure why you need the full diff? I did not dig in to the code deep enough, but there is such a thing as `git status -s` which can be executed **inside** the `HOOK_EXEC_PATH` (so the CD needs to come **first**) and it will give you a list of changed files **relative** to the dir you are in:
```
M src/path/to/my/BaseController.php
R  src/path/to/my/StatusController.php -> src/path/to/my/StatusController2.php
?? ../test.php
?? test.log
```
But that might not be enough for what GrumPHP does with that output? It will not only show staged stuff and uses colour coding do differentiate between staged and not staged so that's probably a no go

3. Find a way to make `git diff` display relative paths. A way to do this would be to simply adjust the existing command you currently use to this: `git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged --src-prefix=a/../ --dst-prefix=b/../`. Note the addition of the `--src-prefix` and `--dst-prefix` which would result in:
```diff
diff --git a/../project/src/path/to/my/file.php b/../project/src/path/to/my/file.php
index c9bdffd945057f1202a27c150dc8512139eab3a0..ec20fbe03e4a01d40445716892f6162562a8dd73 100644
--- a/../project/src/path/to/my/BaseController.php
+++ b/../project/src/path/to/my/BaseController.php
@@ -33,7 +33,7 @@ abstract class BaseController extends Controller
             if ($log) {
                 $this->log($log, 'error');
             }
-            throw $this->createAccessDeniedException($message);
+throw $this->createAccessDeniedException($message);
         }
     }
```
I think option 3 would be quite easy to implement, especially since you already **have** this prefix in the `grumphp.ml` file:
```yml
parameters:
    git_dir: ..
    bin_dir: vendor/bin
```
Handling the trailing slash is a breeze (`$prefix = rtrim($gitDir, '/') . '/';`)

**Comment by mattheo-geoffray** [comment]
Hello!  
Any update on that? 🙂

**Comment by open-it** [comment]
I have the same issue (for the same reason : docker conf outside the project) so an update would be great. :smiley_cat:

**Comment by DylanGD** [comment]
Same issue here :( any news ?

**Comment by veewee** [comment]
This specific case should be fixed in #643. However, there are some other exotic structures still not possible. (will be fixed in upcoming prs)

**Comment by mattheo-geoffray** [comment]
@veewee Great news! Thanks for the fix! 🙂

**Comment by veewee** [comment]
Hello @mattheo-geoffray 
Just wanted to let you know I am finishing up the release.
Feel free to validate if this is working for you : https://github.com/phpro/grumphp/pull/644

I'll close this issue for now. Feel free to open up a new one or comment on the open PR if there is an issue related to that.

**Comment by mattheo-geoffray** [comment]
Hi @veewee 

Really great news here!  
I will try it soon and let you know 🙂 

Thanks for your work on that!

**Comment by mattheo-geoffray** [comment]
Hi @veewee !  
I have just tested the last v0.16.0 release 🙂 

Maybe I am missing something here, I add these lines to the `composer.json` at the very root of my project
```
    "extra": {
        "grumphp": {
            "config-default-path": "./grumphp.yml",
            "project-path": "./magento/src"
        }
    },
```

But when I try to run GrumPHP it take the executable in the `vendor/bin` of my sub-project.

```
|- .git/
|- magento
       |- src
            |- composer.json
            |- vendor/bin/phpcs
|- composer.json
|- vendor/bin/phpcs
|- grumphp.yml
```
When I run GrumPHP the executable locator `\GrumPHP\Locator\ExternalCommand::locate` will return `/path/to/my/project/magento/src/vendor/bin` and not `/path/to/my/project/vendor/bin`  
Causing some librairies like PHPCS to not find the custom standard for example.
 
Is that a normal behavior with the last v0.16.0? 

Thank you!

**Comment by mattheo-geoffray** [comment]
It seems that `$workingDir = getcwd();` in `\GrumPHP\Locator\GuessedPathsLocator::locate` is the reason that it is not the right Composer vendor

**Comment by mattheo-geoffray** [comment]
@veewee I saw: https://github.com/phpro/grumphp/blob/master/doc/installation/exotic.md#changing-paths-by-using-environment-variables   
Is there a way in GrumPHP config to specify a `.env` file?

**Comment by mattheo-geoffray** [comment]
@veewee I found the issue in `\GrumPHP\Util\ComposerFile::ensureProjectBinDirInSystemPath`
```
// add the bin dir to the PATH to make local binaries of deps usable in scripts
$binDir = realpath($this->getBinDir());
```
It does not take care of `$_SERVER['GRUMPHP_COMPOSER_DIR']` or `$_SERVER['GRUMPHP_BIN_DIR']`

**Comment by veewee** [comment]
Hello @mattheo-geoffray,

I answered most questions in the other tickets you created. Lets continue the discussion in there.
