### ISSUE TITLE
Add EnvVariableLocator in order to use automatically .env file

### ISSUE THREAD

**Issue by mattheo-geoffray** [phpro/grumphp#676]
| Q               | A
| --------------- | ---
| Version         | `0.16.0`
| Bug?            | no
| New feature?    | yes
| Question?       | no
| Documentation?  | no
| Related tickets | comma-separated list of related tickets

Since the version `0.16.0` we can use environment variables to change GrumPHP logic as it explained here: https://github.com/phpro/grumphp/blob/master/doc/installation/exotic.md#changing-paths-by-using-environment-variables   

The issue here it that there is no logic to include environment variables in GrumPHP.   

Maybe we can use https://symfony.com/doc/current/components/dotenv.html to load environment variables?
To test and validated I tried to simply add at the top of `\GrumPHP\Locator\GuessedPathsLocator::locate`
```php
$dotenv = new Dotenv();
$dotenv->load('/path/to/.env');
```
and it works well.

Or maybe there is already an other solution for that?

Thank you!

**Comment by veewee** [comment]
Hello @mattheo-geoffray,

I agree that these environment variables are currently a bit hard to use. We should indeed make this a bit more developer friendly.
I thought about adding something similar during development of the feature as well. But there are some 'problems' with this:

- I don't really want to force people to create 2 config files
- I don't want to add more path guessing (it already does A LOT at the moment)
- Ideally, the env vars should be loaded before any guessing starts.
- We cannot place it in grumphp.yml, because we don't know were it is located before the guessing finished.

Do you have any suggestings on how you would like to tell GrumPHP where the .env file is located?

I was thinking about using `GRUMPHP_DOT_ENV` at that moment, but it would still be something you'll need to add while running the command...

For git hooks it is less of a problem: I was thinking about auto adding all `GRUMPHP_` and all `git_hook_variables` on top of the git hooks. Just to make that part easier.

Suggestions are highly welcome!

**Comment by mattheo-geoffray** [comment]
@veewee Regarding the fact that the env variables available to override GrumPHP are starting by `GRUMPHP` the top of GIT hooks seems right to me.  
  
To include them more easily and leave the choice to the developer to add one more config file or not it is possible to repeat the same logic as the `docker-compose.yml` files with their `environment` node and also the `env_file` node in yml .(https://docs.docker.com/compose/environment-variables/)
With that you can inject the environment variables directly with the node or with the `env_file` instruction.  

What do you think about it?

**Comment by veewee** [comment]
That would indeed be great.

The problem with that is:
The path guessing (which consumes the env variables) takes place before the config file is loaded.
This means that we currently won't be able to change the way GrumPHP determines the paths by specifying them in the grumphp.yml file.

This means it would be able to add the parameters, but they won't influence where stuff is located.
(Unless we restart the path guessing a second time after loading the paths regularly, which seems too much overkill)

**Comment by mattheo-geoffray** [comment]
@veewee Correct me if I am wrong but path guessing is using only these variables:
```
GRUMPHP_PROJECT_DIR=...
GRUMPHP_GIT_WORKING_DIR=....
GRUMPHP_GIT_REPOSITORY_DIR=...
GRUMPHP_COMPOSER_DIR=...
GRUMPHP_BIN_DIR=...
```

So we can have two logics:
- auto include `GRUMPHP_*` variables in top of GIT hook to be loaded before path guessing
- the "docker-compose" logic after path guessing for people who want to use env variables in extensions for exemple. IMO regarding the fact that other variables can not impact path guessing it will be not an issue to load the rest of them after it

**Comment by veewee** [comment]
Adding the variables on top of the git hooks  won't fix the situation for the `run` command though.
I would rather find a solution that works for all run contexts.
Lets keep this one open for a while and see what other ideas pop up.

**Comment by veewee** [comment]
What could work:

- Run path guessing as it is right now
- Build the container
- Register grumphp.yml env  + env_file in a compiler pass. 
- Directly after the container was built: Do a "simpler" second guess as in : use env or previous guessed version and replace the guessed paths.
- Register the second guess as the GuessedPaths synthetic service.

If these actions follow each other very quickly, it might just work in every context.
(Even without writing the env vars to the hook file)

**Comment by mattheo-geoffray** [comment]
@veewee Seems good! Just taking into account the different events dispatched and extensions between the steps which can rely on these guessed paths 
Maybe there are not?

**Comment by veewee** [comment]
The idea is to run the logic as described above before the container has been fully configured (and before any event has been triggered)
Extensions however, won't be able to access the GuessedPaths in compiler passes (since they are registered afterwards). But that is not possible ATM anyways. They do can inject it as a service. (but even then : it's better to inject the Paths util)

**Comment by minterior** [comment]
Hello, this would be an awesome feature.
But I think you are leaving out the possibility of passing environment variables to custom scripts. And I am referring to the configuration variable  `EXEC_GRUMPHP_COMMAND` which could be `my-script.sh` needing some environment variable (it is exactly my use case right now). In that case, exporting the environment variables in the hook file would be the only valid solution I guess. We might have a separate variable like:
```
git_hook_variables:
  EXEC_GRUMPHP_COMMAND: 'my-script.sh'
  ENV:
  - ENV_VAR1: foo
  - ENV_VAR2: bar
```
Those exported variables could also be available within the PHP process running GrumPHP, so having two different env definitions would not be necessary or overcomplicated.

**Comment by veewee** [comment]
Hello,

I wanted to let you know that I added a little POC in #785.
Feel free to play around with it (it should work) and give me some feedback.

**Comment by mattheo-geoffray** [comment]
Hi @veewee ,

oh nice I will definitely check that and let you know!

Thank you for the update!

**Comment by mattheo-geoffray** [comment]
@veewee OK great! I will check that, thank you for this feature!
