### ISSUE TITLE
add --skip-success-output to commit-msg

### ISSUE THREAD

**Issue by ctrl-f5** [phpro/grumphp#76]
The success and error messages are way to big and distracting, displaying the massive logo every time, the pre-commit hook can already skip this output, but the commit-msg does not have this option.

Maybe it would be best to make this configurable in grumphp.yml?

**Comment by veewee** [comment]
The logo can be disabled already by following configuration:

```yaml
parameters:
  ascii:
    failed: ~
    succeeded: ~
```

The skip-success-output is added to the pre-commit so that the commit-msg can still fail. It might be a good idea to add this option to the commit-msg command as well.

If you don't want the command to output anything, you might want to add the --quiet option to the hook. Don't think this is very usefull, but it is an option.

**Comment by ctrl-f5** [comment]
yes, disabling the ascii images is exactly what I was looking for, thanks
